package irvine.math.partition;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.function.BiFunction;

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.z.Z;

/**
 * Utility methods for small integer arrays with descending values (the parts),
 * as they are generated by <code>IntegerPartition</code>.
 * @author Georg Fischer
 */
public final class PartitionUtils {

  /**
   * Empty constructor.
   */
  public PartitionUtils() {
  }

  /**
   * Determine whether a number is a part.
   * @param p partition
   * @param part number to be tested for membership
   * @return true for a part, false otherwise
   */
  public static boolean isPart(final int[] p, int part) {
    final int len = p.length;
    for(int i = 0; i < len; ++i) {
      if (part > p[i]) { 
        return false;
      }
      if (part == p[i]) { 
        return true;
      }
    }
    return false;
  }

  /**
   * Get the least part.
   * @param p partition
   * @return minimal part
   */
  public static int min(final int[] p) {
    return p[p.length - 1];
  }

  /**
   * Get the greatest part.
   * @param p partition
   * @return maximal part
   */
  public static int max(final int[] p) {
    return p[0];
  }

  /**
   * Get the counts of the even and the odd parts, without multiplicity.
   * @param p partition
   * @return [evenCount, oddCount]
   */
  public static int[] evenOddCounts(final int[] p) {
    int evenCount = 0;
    int oddCount = 0;
    int old = 0;
    for (int n : p) {
      if (old != n) {
        old = n;
        if ((n&1) == 0) {
          ++evenCount;
        } else {
          ++oddCount;
        }
        if (n == 1) {
          return new int[] { evenCount, oddCount };
        }
      } // else old == n: ignore
    }
    return new int[] { evenCount, oddCount };
  }

  /**
   * Get the sums of the even and the odd parts, with multiplicity.
   * @param p partition
   * @return [evenCount, oddCount]
   */
  public static int[] evenOddSums(final int[] p) {
    int evenSum = 0;
    int oddSum = 0;
    for (int n : p) {
      if ((n&1) == 0) {
        evenSum += n;
      } else {
        oddSum += n;
      }
    }
    return new int[] { evenSum, oddSum };
  }

  /**
   * Get the count of numbers that are congruent <code>res mod base</code>, without multiplicity.
   * @param p partition
   * @param base take the modulus to this base
   * @param res required residue
   * @return number of parts in <code>p</code> that fulfill the modulus condition
   */
  public static int modCount(final int[] p, int base, int res) {
    int count = 0;
    int old = 0;
    for (int n : p) {
      if (old != n) {
        old = n;
        if (n % base == res) {
          ++count;
        }
        if (n == 1) {
          return count;
        }
      } // else old == n: ignore
    }
    return count;
  }

  /**
   * Get the mean (average of parts).
   * @param p partition
   * @return sum(parts)/(number of parts), many a fraction
   */
  public static Q mean(final int[] p) {
    int sum = 0;
    for (int n : p) {
      sum += n;
    }
    return new Q(sum, p.length);
  }

  /**
   * Get the median, that is the average of the 2 middle parts if the length is even,
   * and the middle part if the length is odd.
   * @param p partition
   * @return a fraction
   */
  public static Q median(final int[] p) {
    final int len = p.length;
    if ((len&1) == 1) {
      return new Q(p[len/2]);
    }
    return new Q(p[len/2 - 1] + p[len/2], 2);
  }

  /**
   * Get the count of distinct parts.
   * @param p partition
   * @return number of distinct parts
   */
  public static int distinctCount(final int[] p) {
    int count = 0;
    int old = 0;
    for (int n : p) {
      if (old != n) {
        old = n;
        ++count;
        if (n == 1) {
          return count;
        }
      } // else old == n: ignore
    }
    return count;
 }

  /**
   * Get the count of numbers that have multiplicity 1.
   * @param p partition
   * @return number of parts in <code>p</code> that occur only once
   */
  public static int singleCount(final int[] p) {
    final int len = p.length;
    if (len == 1) {
      return 1; // p0
    }
    int count = 0;
    int p0 = p[0];
    int p1 = p[1];
    if (p0 > p1) {
      ++count; // p0
    }
    if (len == 2) {
      return count * 2;
    }
    int p2 = 0;
    for (int i = 2; i < len; ++i) {
      p2 = p[i];
      if (p0 > p1 && p1 > p2) {
        ++count; // p1
      }
      p0 = p1;
      p1 = p2;
    }
    if (p0 > p1) {
      ++count; // p2
    }
    return count;
  }

  /**
   * Get the count of numbers that have multiplicity &gt; 1.
   * @param p partition
   * @return number of parts in <code>p</code> that occur more than once
   */
  public static int multiCount(final int[] p) {
    final int len = p.length;
    if (len == 1) {
      return 0; 
    }
    int count = 0;
    int p0 = p[0];
    int p1 = p[1];
    if (len == 2) {
      return p0 == p1 ? 1 : 0;
    }
    int p2 = 0;
    for (int i = 2; i < len; ++i) {
      p2 = p[i];
      if (p0 == p1 && p1 > p2) {
        ++count; // p1
      }
      p0 = p1;
      p1 = p2;
    }
    if (p0 == p1) {
      ++count; // p2
    }
    return count;
  }

  /**
   * Print the results of all methods for the integer partitions of the given argument.
   * @param args number
   */
  public static void main(final String[] args) {
    final IntegerPartition ip = new IntegerPartition(Integer.parseInt(args[0]));
    int[] p;
    while ((p = ip.next()) != null) {
      System.out.println(Arrays.toString(p));
      System.out.println("  evenOddCounts:   " + Arrays.toString(evenOddCounts(p)));
      System.out.println("  evenOddSums:     " + Arrays.toString(evenOddSums(p)));
      System.out.println("  min:             " + min(p));
      System.out.println("  max:             " + max(p));
      System.out.println("  singleCount:     " + singleCount(p));
      System.out.println("  multiCount:      " + multiCount(p));
      System.out.println("  isPart(p,3):     " + isPart(p, 3));
      System.out.println("  modCount(p,5,3): " + modCount(p, 5, 3));
      System.out.println("  distinctCount:   " + distinctCount(p));
      System.out.println("  mean:            " + mean(p));
      System.out.println("  median:          " + median(p));
    }
  }
}
