package irvine.oeis.a035;
// Generated by gen_seq4.pl A035536 0 0  at (DATE)
// DO NOT EDIT here!
/* 
    (maple), alois heinz:
    b := proc(n, i, c) option remember; `if`(n=0,
      `if`(c=0, 1, 0), `if`(i<1, 0, b(n, i-1, c)+
       b(n-i, min(n-i, i), c+[0, 1, -1][1+irem(i, 3)])))
    end:
    seq(b(n,n, 0), n=0..32);
__DATA__
1,0,0,2,0,0,6,0,0,14,0,0,32,0,0,66,0,0,134,0,0,256,0,0
,480,0,0,868,0,0,1540,0,0,2664,0,0,4536,0,0,7574,0,0
,12474,0,0,20234,0,0,32428,0,0,51324,0,0,80388,0,0,124582
,0,0,191310,0,0,291114,0,0,439394,0,0,657936,0,0
*/

import irvine.math.z.Z;
import irvine.math.z.ZUtils;
import irvine.oeis.Sequence;
import java.util.HashMap;

/**
 * A035536 Number of partitions of n with equal number of parts congruent to each of 1 and 2 (mod 3)
 * @author Georg Fischer
 */
public class A035679 implements Sequence {

  private final HashMap<String, Z> mRemember; // simulate "option remember"
  protected final Z[] mModules; // which combination of elements to select
  protected final long mImod; // take i mod this number
  protected int mN; // index of next term
  
  /** Construct with default parameters. */
  public A035769() {
    this(8, 1,2);
  }
    
  /** Construct the sequence. 
   * @param imod take i mod this number
   * @param modules vector of valid values
   */
  public A035679(long imod, long ... modules) {
    mImod = imod;
    mModules = ZUtils.toZ(modules);
    mRemember = new HashMap<String, Z>(1000000); // termNO = 1000 consumes some 6 mio hash map entries
    mN = -1;
  }
    
  protected Z partition (final Z n, final Z i, final Z c) {
    String key = n.toString() + "," + i.toString() + "," + c.toString();
    Z result = mRemember.get(key);
    if (result == null) {
        if (n.equals(Z.ZERO)) {
            result = c.equals(Z.ZERO) ? Z.ONE : Z.ZERO;
        } else {
            if (i.compareTo(Z.ONE) < 0) {
                result = Z.ZERO;
            } else {
                Z n_i = n.subtract(i);
                result = partition(n, i.subtract(Z.ONE), c)
                    .add(partition(n_i, n_i.min(i), c.add(mModules[(int) i.mod(mImod)])));
            }
        }
        mRemember.put(key, result);
    }
    return result;
  }
  
  /**
   * Determine the specific modulus condition to be applied to the partition
   * @return increment for the count 
   */
  protected Z modules(final Z i) {
    return (new Z[] { Z.ZERO, Z.ONE, Z.NEG_ONE })[i.mod(Z.THREE).intValue()];
  }
  
  /**
   * Compute the next term of the sequence
   * @return a specific number of partitions
   */
  @Override
  public Z next() {
    ++mN;
    return partition(Z.valueOf(mN), Z.valueOf(mN), Z.ZERO);
  }

  /**
   * Get the size of the hashmap.
   * @return number of remembered parameter combinations of {@link #partition}.
   */
  public long size() {
  	return mRemember.size();
  }
  
  /**
   * Compute a number of terms for A035536
   * @param args number of terms
   */
  public static void main(final String[] args) {
    int termNo = 64;
    A035536 seq = new A035536();
    if (args.length > 0) {
      try {
        termNo = Integer.parseInt(args[0]);
      } catch (Exception exc) { // ignore
      }
    }
    for (int index = 0; index < termNo; ++index) {
      System.out.println(index + " " + seq.next().toString());
    }
    System.out.println(seq.size() + " parameter sets remembered");
  }
}
