#!perl

# Generate for CC=hypergeon" 
# @(#) $Id$
# 2023-11-10, Georg Fischer
#--------------------------------------------------------
use strict;
use integer;
use warnings;

my $aseqno;
my $cc = "hypergeon";

while (<>) {
    s{\s+\Z}{}; # chompr
    my $line = $_;
    # print "## $line\n";
    if (0) {
    } elsif ($line =~ m{^ *public (A\d+) *\(}) {
        print "$1\t$cc\t";
    #                                 1offset1    2p     2    3q     3    4polys     45    6inits     65
    } elsif ($line =~ m{^     *super\((\-?\d+)\, *(\-?\d+)\, *(\-?\d+)\, *(\"[^\"]+\")(\, *(\"[^\"]+\"))?}) {
        print join("\t", $1, $2, $3, $4, $6 || "\"\"");
    #                                               1      1
    } elsif ($line =~ m{^   *return super\.nextQ\(\)([^\;]+)\;}) {
    	my $expr = $1;
    	$expr =~ s{\bmN\b}{n}g;
        print "\t(n, v) -> v$expr\n";
    }
} # while <>
__DATA__
#----------------------------------------------------------------
#!queue A304936 1   FATAL   Difference  between next()  and a(1):   1   !=  -1
package irvine.oeis.a304;
// Generated by gen_seq4.pl hygeom at 2022-08-06 21:23

import irvine.math.z.Z;
import irvine.oeis.HypergeometricSequence;

/**
 * A304936 a(n) = [x^n] 1/(1 - n*x/(1 - x - n*x/(1 - x - n*x/(1 - x - n*x/(1 - x - n*x/(1 - ...)))))), a continued fraction.
 * @author Georg Fischer
 */
public class A304936 extends HypergeometricSequence {

  private int mN = -1;

  /** Construct the sequence. */
  public A304936() {
    super(0, 2, 1, "[[0,-1],[1, 1],[2],[1, 1]]");
  }

  @Override
  public Z next() {
    ++mN;
    return super.nextQ().multiply(((mN & 1) == 0) ? 1 : -1).num();
  }
}
