package irvine.oeis;

/** 
 * Data tables for {@link McKayThompsonSequence}.
 * @author Georg Fischer
 * Derived from <code>moonshine.py</code> of
 * David A. Madore <david.madore@ens.fr> - 2007-07-31 - Public Domain.
 * Cf. <code>https://web.archive.org/web/20130925003421/http://mathforum.org/kb/thread.jspa?forumID=253&threadID=1602206&messageID=5836094</code>
 * This class was generated by https://github.com/gfis/joeis-lite/internal/fischer/mckay_tables.pl on 2020-10-02
 * DO NOT EDIT HERE !
 */
public class McKayThompsonTables {

  /** Valid class codes */
  private static final int[] sValidClasses = new int[] 
    { 0x010 /*01A */
    , 0x020 /*02A */, 0x021 /*02B */
    , 0x030 /*03A */, 0x031 /*03B */, 0x032 /*03C */
    , 0x040 /*04A */, 0x041 /*04B */, 0x042 /*04C */, 0x043 /*04D */
    , 0x050 /*05A */, 0x051 /*05B */
    , 0x060 /*06A */, 0x061 /*06B */, 0x062 /*06C */, 0x063 /*06D */, 0x064 /*06E */, 0x065 /*06F */
    , 0x070 /*07A */, 0x071 /*07B */
    , 0x080 /*08A */, 0x081 /*08B */, 0x082 /*08C */, 0x083 /*08D */, 0x084 /*08E */, 0x085 /*08F */
    , 0x090 /*09A */, 0x091 /*09B */
    , 0x100 /*10A */, 0x101 /*10B */, 0x102 /*10C */, 0x103 /*10D */, 0x104 /*10E */
    , 0x110 /*11A */
    , 0x120 /*12A */, 0x121 /*12B */, 0x122 /*12C */, 0x123 /*12D */, 0x124 /*12E */, 0x125 /*12F */, 0x126 /*12G */, 0x127 /*12H */, 0x128 /*12I */, 0x129 /*12J */
    , 0x130 /*13A */, 0x131 /*13B */
    , 0x140 /*14A */, 0x141 /*14B */, 0x142 /*14C */
    , 0x150 /*15A */, 0x151 /*15B */, 0x152 /*15C */, 0x153 /*15D */
    , 0x160 /*16A */, 0x161 /*16B */, 0x162 /*16C */
    , 0x170 /*17A */
    , 0x180 /*18A */, 0x181 /*18B */, 0x182 /*18C */, 0x183 /*18D */, 0x184 /*18E */
    , 0x190 /*19A */
    , 0x200 /*20A */, 0x201 /*20B */, 0x202 /*20C */, 0x203 /*20D */, 0x204 /*20E */, 0x205 /*20F */
    , 0x210 /*21A */, 0x211 /*21B */, 0x212 /*21C */, 0x213 /*21D */
    , 0x220 /*22A */, 0x221 /*22B */
    , 0x230 /*23A */, 0x231 /*23B */
    , 0x240 /*24A */, 0x241 /*24B */, 0x242 /*24C */, 0x243 /*24D */, 0x244 /*24E */, 0x245 /*24F */, 0x246 /*24G */, 0x247 /*24H */, 0x248 /*24I */, 0x249 /*24J */
    , 0x250 /*25A */
    , 0x260 /*26A */, 0x261 /*26B */
    , 0x270 /*27A */, 0x271 /*27B */
    , 0x280 /*28A */, 0x281 /*28B */, 0x282 /*28C */, 0x283 /*28D */
    , 0x290 /*29A */
    , 0x300 /*30A */, 0x301 /*30B */, 0x302 /*30C */, 0x303 /*30D */, 0x304 /*30E */, 0x305 /*30F */, 0x306 /*30G */
    , 0x310 /*31A */, 0x311 /*31B */
    , 0x320 /*32A */, 0x321 /*32B */
    , 0x330 /*33A */, 0x331 /*33B */
    , 0x340 /*34A */
    , 0x350 /*35A */, 0x351 /*35B */
    , 0x360 /*36A */, 0x361 /*36B */, 0x362 /*36C */, 0x363 /*36D */
    , 0x380 /*38A */
    , 0x390 /*39A */, 0x391 /*39B */, 0x392 /*39C */, 0x393 /*39D */
    , 0x400 /*40A */, 0x401 /*40B */, 0x402 /*40C */, 0x403 /*40D */
    , 0x410 /*41A */
    , 0x420 /*42A */, 0x421 /*42B */, 0x422 /*42C */, 0x423 /*42D */
    , 0x440 /*44A */, 0x441 /*44B */
    , 0x450 /*45A */
    , 0x460 /*46A */, 0x461 /*46B */, 0x462 /*46C */, 0x463 /*46D */
    , 0x470 /*47A */, 0x471 /*47B */
    , 0x480 /*48A */
    , 0x500 /*50A */
    , 0x510 /*51A */
    , 0x520 /*52A */, 0x521 /*52B */
    , 0x540 /*54A */
    , 0x550 /*55A */
    , 0x560 /*56A */, 0x561 /*56B */, 0x562 /*56C */
    , 0x570 /*57A */
    , 0x590 /*59A */, 0x591 /*59B */
    , 0x600 /*60A */, 0x601 /*60B */, 0x602 /*60C */, 0x603 /*60D */, 0x604 /*60E */, 0x605 /*60F */
    , 0x620 /*62A */, 0x621 /*62B */
    , 0x660 /*66A */, 0x661 /*66B */
    , 0x680 /*68A */
    , 0x690 /*69A */, 0x691 /*69B */
    , 0x700 /*70A */, 0x701 /*70B */
    , 0x710 /*71A */, 0x711 /*71B */
    , 0x780 /*78A */, 0x781 /*78B */, 0x782 /*78C */
    , 0x840 /*84A */, 0x841 /*84B */, 0x842 /*84C */
    , 0x870 /*87A */, 0x871 /*87B */
    , 0x880 /*88A */, 0x881 /*88B */
    , 0x920 /*92A */, 0x921 /*92B */
    , 0x930 /*93A */, 0x931 /*93B */
    , 0x940 /*94A */, 0x941 /*94B */
    , 0x950 /*95A */, 0x951 /*95B */
    , 0xa40 /*104A*/, 0xa41 /*104B*/
    , 0xa50 /*105A*/
    , 0xb00 /*110A*/
    , 0xb90 /*119A*/, 0xb91 /*119B*/, 0xb92 /*119C*/
    }; // sValidClasses
    
  /** Class powers */
  private static final int[][] sClassPowers = new int[][] 
    { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x010 */ new int[] { 0x010, 0x010, 0x010, 0x010, 0x010, 0x010, 0x010, 0x010, 0x010, 0x010 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x020 */ new int[] { 0x010, 0x020, 0x010, 0x020, 0x010, 0x020, 0x010, 0x020, 0x010, 0x020 }
    , /* 0x021 */ new int[] { 0x010, 0x021, 0x010, 0x021, 0x010, 0x021, 0x010, 0x021, 0x010, 0x021 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x030 */ new int[] { 0x010, 0x030, 0x030, 0x010, 0x030, 0x030, 0x010, 0x030, 0x030, 0x010 }
    , /* 0x031 */ new int[] { 0x010, 0x031, 0x031, 0x010, 0x031, 0x031, 0x010, 0x031, 0x031, 0x010 }
    , /* 0x032 */ new int[] { 0x010, 0x032, 0x032, 0x010, 0x032, 0x032, 0x010, 0x032, 0x032, 0x010 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x040 */ new int[] { 0x010, 0x040, 0x021, 0x040, 0x010, 0x040, 0x021, 0x040, 0x010, 0x040 }
    , /* 0x041 */ new int[] { 0x010, 0x041, 0x020, 0x041, 0x010, 0x041, 0x020, 0x041, 0x010, 0x041 }
    , /* 0x042 */ new int[] { 0x010, 0x042, 0x021, 0x042, 0x010, 0x042, 0x021, 0x042, 0x010, 0x042 }
    , /* 0x043 */ new int[] { 0x010, 0x043, 0x021, 0x043, 0x010, 0x043, 0x021, 0x043, 0x010, 0x043 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x050 */ new int[] { 0x010, 0x050, 0x050, 0x050, 0x050, 0x010, 0x050, 0x050, 0x050, 0x050 }
    , /* 0x051 */ new int[] { 0x010, 0x051, 0x051, 0x051, 0x051, 0x010, 0x051, 0x051, 0x051, 0x051 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x060 */ new int[] { 0x010, 0x060, 0x030, 0x020, 0x030, 0x060, 0x010, 0x060, 0x030, 0x020 }
    , /* 0x061 */ new int[] { 0x010, 0x061, 0x031, 0x021, 0x031, 0x061, 0x010, 0x061, 0x031, 0x021 }
    , /* 0x062 */ new int[] { 0x010, 0x062, 0x030, 0x021, 0x030, 0x062, 0x010, 0x062, 0x030, 0x021 }
    , /* 0x063 */ new int[] { 0x010, 0x063, 0x031, 0x020, 0x031, 0x063, 0x010, 0x063, 0x031, 0x020 }
    , /* 0x064 */ new int[] { 0x010, 0x064, 0x031, 0x021, 0x031, 0x064, 0x010, 0x064, 0x031, 0x021 }
    , /* 0x065 */ new int[] { 0x010, 0x065, 0x032, 0x021, 0x032, 0x065, 0x010, 0x065, 0x032, 0x021 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x070 */ new int[] { 0x010, 0x070, 0x070, 0x070, 0x070, 0x070, 0x070, 0x010, 0x070, 0x070 }
    , /* 0x071 */ new int[] { 0x010, 0x071, 0x071, 0x071, 0x071, 0x071, 0x071, 0x010, 0x071, 0x071 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x080 */ new int[] { 0x010, 0x080, 0x042, 0x080, 0x021, 0x080, 0x042, 0x080, 0x010, 0x080 }
    , /* 0x081 */ new int[] { 0x010, 0x081, 0x040, 0x081, 0x021, 0x081, 0x040, 0x081, 0x010, 0x081 }
    , /* 0x082 */ new int[] { 0x010, 0x082, 0x041, 0x082, 0x020, 0x082, 0x041, 0x082, 0x010, 0x082 }
    , /* 0x083 */ new int[] { 0x010, 0x083, 0x042, 0x083, 0x021, 0x083, 0x042, 0x083, 0x010, 0x083 }
    , /* 0x084 */ new int[] { 0x010, 0x084, 0x042, 0x084, 0x021, 0x084, 0x042, 0x084, 0x010, 0x084 }
    , /* 0x085 */ new int[] { 0x010, 0x085, 0x043, 0x085, 0x021, 0x085, 0x043, 0x085, 0x010, 0x085 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x090 */ new int[] { 0x010, 0x090, 0x090, 0x031, 0x090, 0x090, 0x031, 0x090, 0x090, 0x010 }
    , /* 0x091 */ new int[] { 0x010, 0x091, 0x091, 0x031, 0x091, 0x091, 0x031, 0x091, 0x091, 0x010 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x100 */ new int[] { 0x010, 0x100, 0x050, 0x100, 0x050, 0x020, 0x050, 0x100, 0x050, 0x100 }
    , /* 0x101 */ new int[] { 0x010, 0x101, 0x050, 0x101, 0x050, 0x021, 0x050, 0x101, 0x050, 0x101 }
    , /* 0x102 */ new int[] { 0x010, 0x102, 0x051, 0x102, 0x051, 0x020, 0x051, 0x102, 0x051, 0x102 }
    , /* 0x103 */ new int[] { 0x010, 0x103, 0x051, 0x103, 0x051, 0x021, 0x051, 0x103, 0x051, 0x103 }
    , /* 0x104 */ new int[] { 0x010, 0x104, 0x051, 0x104, 0x051, 0x021, 0x051, 0x104, 0x051, 0x104 }, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x110 */ new int[] { 0x010, 0x110, 0x110, 0x110, 0x110, 0x110, 0x110, 0x110, 0x110, 0x110 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x120 */ new int[] { 0x010, 0x120, 0x062, 0x040, 0x030, 0x120, 0x021, 0x120, 0x030, 0x040 }
    , /* 0x121 */ new int[] { 0x010, 0x121, 0x064, 0x040, 0x031, 0x121, 0x021, 0x121, 0x031, 0x040 }
    , /* 0x122 */ new int[] { 0x010, 0x122, 0x060, 0x041, 0x030, 0x122, 0x020, 0x122, 0x030, 0x041 }
    , /* 0x123 */ new int[] { 0x010, 0x123, 0x065, 0x040, 0x032, 0x123, 0x021, 0x123, 0x032, 0x040 }
    , /* 0x124 */ new int[] { 0x010, 0x124, 0x062, 0x042, 0x030, 0x124, 0x021, 0x124, 0x030, 0x042 }
    , /* 0x125 */ new int[] { 0x010, 0x125, 0x061, 0x043, 0x031, 0x125, 0x021, 0x125, 0x031, 0x043 }
    , /* 0x126 */ new int[] { 0x010, 0x126, 0x063, 0x041, 0x031, 0x126, 0x020, 0x126, 0x031, 0x041 }
    , /* 0x127 */ new int[] { 0x010, 0x127, 0x064, 0x042, 0x031, 0x127, 0x021, 0x127, 0x031, 0x042 }
    , /* 0x128 */ new int[] { 0x010, 0x128, 0x064, 0x042, 0x031, 0x128, 0x021, 0x128, 0x031, 0x042 }
    , /* 0x129 */ new int[] { 0x010, 0x129, 0x065, 0x043, 0x032, 0x129, 0x021, 0x129, 0x032, 0x043 }, null, null, null, null, null, null
    , /* 0x130 */ new int[] { 0x010, 0x130, 0x130, 0x130, 0x130, 0x130, 0x130, 0x130, 0x130, 0x130 }
    , /* 0x131 */ new int[] { 0x010, 0x131, 0x131, 0x131, 0x131, 0x131, 0x131, 0x131, 0x131, 0x131 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x140 */ new int[] { 0x010, 0x140, 0x070, 0x140, 0x070, 0x140, 0x070, 0x020, 0x070, 0x140 }
    , /* 0x141 */ new int[] { 0x010, 0x141, 0x070, 0x141, 0x070, 0x141, 0x070, 0x021, 0x070, 0x141 }
    , /* 0x142 */ new int[] { 0x010, 0x142, 0x071, 0x142, 0x071, 0x142, 0x071, 0x021, 0x071, 0x142 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x150 */ new int[] { 0x010, 0x150, 0x150, 0x050, 0x150, 0x030, 0x050, 0x150, 0x150, 0x050 }
    , /* 0x151 */ new int[] { 0x010, 0x151, 0x151, 0x050, 0x151, 0x031, 0x050, 0x151, 0x151, 0x050 }
    , /* 0x152 */ new int[] { 0x010, 0x152, 0x152, 0x051, 0x152, 0x031, 0x051, 0x152, 0x152, 0x051 }
    , /* 0x153 */ new int[] { 0x010, 0x153, 0x153, 0x051, 0x153, 0x032, 0x051, 0x153, 0x153, 0x051 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x160 */ new int[] { 0x010, 0x160, 0x080, 0x160, 0x042, 0x160, 0x080, 0x160, 0x021, 0x160 }
    , /* 0x161 */ new int[] { 0x010, 0x161, 0x084, 0x161, 0x042, 0x161, 0x084, 0x161, 0x021, 0x161 }
    , /* 0x162 */ new int[] { 0x010, 0x162, 0x084, 0x162, 0x042, 0x162, 0x084, 0x162, 0x021, 0x162 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x170 */ new int[] { 0x010, 0x170, 0x170, 0x170, 0x170, 0x170, 0x170, 0x170, 0x170, 0x170 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x180 */ new int[] { 0x010, 0x180, 0x091, 0x063, 0x091, 0x180, 0x031, 0x180, 0x091, 0x020 }
    , /* 0x181 */ new int[] { 0x010, 0x181, 0x090, 0x063, 0x090, 0x181, 0x031, 0x181, 0x090, 0x020 }
    , /* 0x182 */ new int[] { 0x010, 0x182, 0x090, 0x064, 0x090, 0x182, 0x031, 0x182, 0x090, 0x021 }
    , /* 0x183 */ new int[] { 0x010, 0x183, 0x091, 0x064, 0x091, 0x183, 0x031, 0x183, 0x091, 0x021 }
    , /* 0x184 */ new int[] { 0x010, 0x184, 0x091, 0x064, 0x091, 0x184, 0x031, 0x184, 0x091, 0x021 }, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x190 */ new int[] { 0x010, 0x190, 0x190, 0x190, 0x190, 0x190, 0x190, 0x190, 0x190, 0x190 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x200 */ new int[] { 0x010, 0x200, 0x101, 0x200, 0x050, 0x040, 0x101, 0x200, 0x050, 0x200 }
    , /* 0x201 */ new int[] { 0x010, 0x201, 0x100, 0x201, 0x050, 0x041, 0x100, 0x201, 0x050, 0x201 }
    , /* 0x202 */ new int[] { 0x010, 0x202, 0x104, 0x202, 0x051, 0x040, 0x104, 0x202, 0x051, 0x202 }
    , /* 0x203 */ new int[] { 0x010, 0x203, 0x101, 0x203, 0x050, 0x043, 0x101, 0x203, 0x050, 0x203 }
    , /* 0x204 */ new int[] { 0x010, 0x204, 0x103, 0x204, 0x051, 0x043, 0x103, 0x204, 0x051, 0x204 }
    , /* 0x205 */ new int[] { 0x010, 0x205, 0x104, 0x205, 0x051, 0x042, 0x104, 0x205, 0x051, 0x205 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x210 */ new int[] { 0x010, 0x210, 0x210, 0x070, 0x210, 0x210, 0x070, 0x030, 0x210, 0x070 }
    , /* 0x211 */ new int[] { 0x010, 0x211, 0x211, 0x071, 0x211, 0x211, 0x071, 0x030, 0x211, 0x071 }
    , /* 0x212 */ new int[] { 0x010, 0x212, 0x212, 0x070, 0x212, 0x212, 0x070, 0x032, 0x212, 0x070 }
    , /* 0x213 */ new int[] { 0x010, 0x213, 0x213, 0x071, 0x213, 0x213, 0x071, 0x031, 0x213, 0x071 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x220 */ new int[] { 0x010, 0x220, 0x110, 0x220, 0x110, 0x220, 0x110, 0x220, 0x110, 0x220 }
    , /* 0x221 */ new int[] { 0x010, 0x221, 0x110, 0x221, 0x110, 0x221, 0x110, 0x221, 0x110, 0x221 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x230 */ new int[] { 0x010, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231 }
    , /* 0x231 */ new int[] { 0x010, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231, 0x230, 0x231 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x240 */ new int[] { 0x010, 0x240, 0x120, 0x081, 0x062, 0x240, 0x040, 0x240, 0x030, 0x081 }
    , /* 0x241 */ new int[] { 0x010, 0x241, 0x124, 0x080, 0x062, 0x241, 0x042, 0x241, 0x030, 0x080 }
    , /* 0x242 */ new int[] { 0x010, 0x242, 0x128, 0x080, 0x064, 0x242, 0x042, 0x242, 0x031, 0x080 }
    , /* 0x243 */ new int[] { 0x010, 0x243, 0x124, 0x083, 0x062, 0x243, 0x042, 0x243, 0x030, 0x083 }
    , /* 0x244 */ new int[] { 0x010, 0x244, 0x123, 0x081, 0x065, 0x244, 0x040, 0x244, 0x032, 0x081 }
    , /* 0x245 */ new int[] { 0x010, 0x245, 0x125, 0x085, 0x061, 0x245, 0x043, 0x245, 0x031, 0x085 }
    , /* 0x246 */ new int[] { 0x010, 0x246, 0x126, 0x082, 0x063, 0x246, 0x041, 0x246, 0x031, 0x082 }
    , /* 0x247 */ new int[] { 0x010, 0x247, 0x127, 0x083, 0x064, 0x247, 0x042, 0x247, 0x031, 0x083 }
    , /* 0x248 */ new int[] { 0x010, 0x248, 0x128, 0x084, 0x064, 0x248, 0x042, 0x248, 0x031, 0x084 }
    , /* 0x249 */ new int[] { 0x010, 0x249, 0x129, 0x085, 0x065, 0x249, 0x043, 0x249, 0x032, 0x085 }, null, null, null, null, null, null
    , /* 0x250 */ new int[] { 0x010, 0x250, 0x250, 0x250, 0x250, 0x051, 0x250, 0x250, 0x250, 0x250 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x260 */ new int[] { 0x010, 0x260, 0x130, 0x260, 0x130, 0x260, 0x130, 0x260, 0x130, 0x260 }
    , /* 0x261 */ new int[] { 0x010, 0x261, 0x131, 0x261, 0x131, 0x261, 0x131, 0x261, 0x131, 0x261 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x270 */ new int[] { 0x010, 0x270, 0x270, 0x091, 0x270, 0x270, 0x091, 0x270, 0x270, 0x031 }
    , /* 0x271 */ new int[] { 0x010, 0x271, 0x271, 0x091, 0x271, 0x271, 0x091, 0x271, 0x271, 0x031 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x280 */ new int[] { 0x010, 0x280, 0x140, 0x280, 0x070, 0x280, 0x140, 0x041, 0x070, 0x280 }
    , /* 0x281 */ new int[] { 0x010, 0x281, 0x141, 0x281, 0x070, 0x281, 0x141, 0x040, 0x070, 0x281 }
    , /* 0x282 */ new int[] { 0x010, 0x282, 0x141, 0x282, 0x070, 0x282, 0x141, 0x042, 0x070, 0x282 }
    , /* 0x283 */ new int[] { 0x010, 0x283, 0x142, 0x283, 0x071, 0x283, 0x142, 0x043, 0x071, 0x283 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x290 */ new int[] { 0x010, 0x290, 0x290, 0x290, 0x290, 0x290, 0x290, 0x290, 0x290, 0x290 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x300 */ new int[] { 0x010, 0x300, 0x152, 0x103, 0x152, 0x061, 0x051, 0x300, 0x152, 0x103 }
    , /* 0x301 */ new int[] { 0x010, 0x301, 0x150, 0x100, 0x150, 0x060, 0x050, 0x301, 0x150, 0x100 }
    , /* 0x302 */ new int[] { 0x010, 0x302, 0x150, 0x101, 0x150, 0x062, 0x050, 0x302, 0x150, 0x101 }
    , /* 0x303 */ new int[] { 0x010, 0x303, 0x151, 0x101, 0x151, 0x061, 0x050, 0x303, 0x151, 0x101 }
    , /* 0x304 */ new int[] { 0x010, 0x304, 0x153, 0x103, 0x153, 0x065, 0x051, 0x304, 0x153, 0x103 }
    , /* 0x305 */ new int[] { 0x010, 0x305, 0x152, 0x102, 0x152, 0x063, 0x051, 0x305, 0x152, 0x102 }
    , /* 0x306 */ new int[] { 0x010, 0x306, 0x152, 0x104, 0x152, 0x064, 0x051, 0x306, 0x152, 0x104 }, null, null, null, null, null, null, null, null, null
    , /* 0x310 */ new int[] { 0x010, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311 }
    , /* 0x311 */ new int[] { 0x010, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311, 0x310, 0x311 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x320 */ new int[] { 0x010, 0x320, 0x161, 0x320, 0x084, 0x320, 0x161, 0x320, 0x042, 0x320 }
    , /* 0x321 */ new int[] { 0x010, 0x321, 0x162, 0x321, 0x084, 0x321, 0x162, 0x321, 0x042, 0x321 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x330 */ new int[] { 0x010, 0x330, 0x330, 0x110, 0x330, 0x330, 0x110, 0x330, 0x330, 0x110 }
    , /* 0x331 */ new int[] { 0x010, 0x331, 0x331, 0x110, 0x331, 0x331, 0x110, 0x331, 0x331, 0x110 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x340 */ new int[] { 0x010, 0x340, 0x170, 0x340, 0x170, 0x340, 0x170, 0x340, 0x170, 0x340 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x350 */ new int[] { 0x010, 0x350, 0x350, 0x350, 0x350, 0x070, 0x350, 0x050, 0x350, 0x350 }
    , /* 0x351 */ new int[] { 0x010, 0x351, 0x351, 0x351, 0x351, 0x071, 0x351, 0x051, 0x351, 0x351 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x360 */ new int[] { 0x010, 0x360, 0x182, 0x121, 0x090, 0x360, 0x064, 0x360, 0x090, 0x040 }
    , /* 0x361 */ new int[] { 0x010, 0x361, 0x183, 0x121, 0x091, 0x361, 0x064, 0x361, 0x091, 0x040 }
    , /* 0x362 */ new int[] { 0x010, 0x362, 0x181, 0x126, 0x090, 0x362, 0x063, 0x362, 0x090, 0x041 }
    , /* 0x363 */ new int[] { 0x010, 0x363, 0x183, 0x128, 0x091, 0x363, 0x064, 0x363, 0x091, 0x042 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x380 */ new int[] { 0x010, 0x380, 0x190, 0x380, 0x190, 0x380, 0x190, 0x380, 0x190, 0x380 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x390 */ new int[] { 0x010, 0x390, 0x390, 0x130, 0x390, 0x390, 0x130, 0x390, 0x390, 0x130 }
    , /* 0x391 */ new int[] { 0x010, 0x391, 0x391, 0x130, 0x391, 0x391, 0x130, 0x391, 0x391, 0x130 }
    , /* 0x392 */ new int[] { 0x010, 0x392, 0x393, 0x392, 0x393, 0x131, 0x392, 0x393, 0x392, 0x393, 0x131, 0x392, 0x393, 0x392, 0x393, 0x131 }
    , /* 0x393 */ new int[] { 0x010, 0x392, 0x393, 0x392, 0x393, 0x131, 0x392, 0x393, 0x392, 0x393, 0x131, 0x392, 0x393, 0x392, 0x393, 0x131 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x400 */ new int[] { 0x010, 0x400, 0x201, 0x400, 0x100, 0x082, 0x201, 0x400, 0x050, 0x400 }
    , /* 0x401 */ new int[] { 0x010, 0x401, 0x200, 0x401, 0x101, 0x081, 0x200, 0x401, 0x050, 0x401 }
    , /* 0x402 */ new int[] { 0x010, 0x402, 0x403, 0x205, 0x402, 0x403, 0x104, 0x083, 0x205, 0x402, 0x403, 0x051, 0x402, 0x403 }
    , /* 0x403 */ new int[] { 0x010, 0x402, 0x403, 0x205, 0x402, 0x403, 0x104, 0x083, 0x205, 0x402, 0x403, 0x051, 0x402, 0x403 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x410 */ new int[] { 0x010, 0x410, 0x410, 0x410, 0x410, 0x410, 0x410, 0x410, 0x410, 0x410 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x420 */ new int[] { 0x010, 0x420, 0x210, 0x140, 0x210, 0x420, 0x070, 0x060, 0x210, 0x140 }
    , /* 0x421 */ new int[] { 0x010, 0x421, 0x213, 0x142, 0x213, 0x421, 0x071, 0x061, 0x213, 0x142 }
    , /* 0x422 */ new int[] { 0x010, 0x422, 0x212, 0x141, 0x212, 0x422, 0x070, 0x065, 0x212, 0x141 }
    , /* 0x423 */ new int[] { 0x010, 0x423, 0x211, 0x142, 0x211, 0x423, 0x071, 0x062, 0x211, 0x142 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x440 */ new int[] { 0x010, 0x440, 0x441, 0x221, 0x440, 0x441, 0x110, 0x440, 0x441, 0x221, 0x440, 0x441, 0x110, 0x440, 0x441 }
    , /* 0x441 */ new int[] { 0x010, 0x440, 0x441, 0x221, 0x440, 0x441, 0x110, 0x440, 0x441, 0x221, 0x440, 0x441, 0x110, 0x440, 0x441 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x450 */ new int[] { 0x010, 0x450, 0x450, 0x151, 0x450, 0x090, 0x151, 0x450, 0x450, 0x050 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x460 */ new int[] { 0x010, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461 }
    , /* 0x461 */ new int[] { 0x010, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461, 0x230, 0x231, 0x460, 0x461 }
    , /* 0x462 */ new int[] { 0x010, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463 }
    , /* 0x463 */ new int[] { 0x010, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463, 0x230, 0x231, 0x462, 0x463 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x470 */ new int[] { 0x010, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471 }
    , /* 0x471 */ new int[] { 0x010, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471, 0x470, 0x471 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x480 */ new int[] { 0x010, 0x480, 0x241, 0x160, 0x124, 0x480, 0x080, 0x480, 0x062, 0x160 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x500 */ new int[] { 0x010, 0x500, 0x250, 0x500, 0x250, 0x102, 0x250, 0x500, 0x250, 0x500 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x510 */ new int[] { 0x010, 0x510, 0x510, 0x170, 0x510, 0x510, 0x170, 0x510, 0x510, 0x170 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x520 */ new int[] { 0x010, 0x520, 0x260, 0x520, 0x130, 0x520, 0x260, 0x520, 0x130, 0x520 }
    , /* 0x521 */ new int[] { 0x010, 0x521, 0x261, 0x521, 0x131, 0x521, 0x261, 0x521, 0x131, 0x521 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x540 */ new int[] { 0x010, 0x540, 0x270, 0x180, 0x270, 0x540, 0x091, 0x540, 0x270, 0x063 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x550 */ new int[] { 0x010, 0x550, 0x550, 0x550, 0x550, 0x110, 0x550, 0x550, 0x550, 0x550 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x560 */ new int[] { 0x010, 0x560, 0x282, 0x560, 0x141, 0x560, 0x282, 0x080, 0x070, 0x560 }
    , /* 0x561 */ new int[] { 0x010, 0x561, 0x562, 0x283, 0x561, 0x562, 0x142, 0x561, 0x562, 0x283, 0x085, 0x071, 0x561, 0x562 }
    , /* 0x562 */ new int[] { 0x010, 0x561, 0x562, 0x283, 0x561, 0x562, 0x142, 0x561, 0x562, 0x283, 0x085, 0x071, 0x561, 0x562 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x570 */ new int[] { 0x010, 0x570, 0x570, 0x190, 0x570, 0x570, 0x190, 0x570, 0x570, 0x190 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x590 */ new int[] { 0x010, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591 }
    , /* 0x591 */ new int[] { 0x010, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591, 0x590, 0x591 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x600 */ new int[] { 0x010, 0x600, 0x301, 0x201, 0x150, 0x122, 0x100, 0x600, 0x150, 0x201 }
    , /* 0x601 */ new int[] { 0x010, 0x601, 0x302, 0x200, 0x150, 0x120, 0x101, 0x601, 0x150, 0x200 }
    , /* 0x602 */ new int[] { 0x010, 0x602, 0x306, 0x202, 0x152, 0x121, 0x104, 0x602, 0x152, 0x202 }
    , /* 0x603 */ new int[] { 0x010, 0x603, 0x306, 0x205, 0x152, 0x127, 0x104, 0x603, 0x152, 0x205 }
    , /* 0x604 */ new int[] { 0x010, 0x604, 0x303, 0x203, 0x151, 0x125, 0x101, 0x604, 0x151, 0x203 }
    , /* 0x605 */ new int[] { 0x010, 0x605, 0x304, 0x204, 0x153, 0x129, 0x103, 0x605, 0x153, 0x204 }, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x620 */ new int[] { 0x010, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621 }
    , /* 0x621 */ new int[] { 0x010, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621, 0x310, 0x311, 0x620, 0x621 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x660 */ new int[] { 0x010, 0x660, 0x331, 0x220, 0x331, 0x660, 0x110, 0x660, 0x331, 0x220 }
    , /* 0x661 */ new int[] { 0x010, 0x661, 0x330, 0x221, 0x330, 0x661, 0x110, 0x661, 0x330, 0x221 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x680 */ new int[] { 0x010, 0x680, 0x340, 0x680, 0x170, 0x680, 0x340, 0x680, 0x170, 0x680 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x690 */ new int[] { 0x010, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231 }
    , /* 0x691 */ new int[] { 0x010, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231, 0x690, 0x691, 0x690, 0x691, 0x230, 0x231 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x700 */ new int[] { 0x010, 0x700, 0x350, 0x700, 0x350, 0x140, 0x350, 0x100, 0x350, 0x700 }
    , /* 0x701 */ new int[] { 0x010, 0x701, 0x351, 0x701, 0x351, 0x142, 0x351, 0x103, 0x351, 0x701 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x710 */ new int[] { 0x010, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711 }
    , /* 0x711 */ new int[] { 0x010, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711, 0x710, 0x711 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x780 */ new int[] { 0x010, 0x780, 0x390, 0x260, 0x390, 0x780, 0x130, 0x780, 0x390, 0x260 }
    , /* 0x781 */ new int[] { 0x010, 0x781, 0x782, 0x392, 0x393, 0x261, 0x392, 0x393, 0x781, 0x782, 0x131, 0x781, 0x782, 0x392, 0x393, 0x261 }
    , /* 0x782 */ new int[] { 0x010, 0x781, 0x782, 0x392, 0x393, 0x261, 0x392, 0x393, 0x781, 0x782, 0x131, 0x781, 0x782, 0x392, 0x393, 0x261 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x840 */ new int[] { 0x010, 0x840, 0x420, 0x280, 0x210, 0x840, 0x140, 0x122, 0x210, 0x280 }
    , /* 0x841 */ new int[] { 0x010, 0x841, 0x421, 0x283, 0x213, 0x841, 0x142, 0x125, 0x213, 0x283 }
    , /* 0x842 */ new int[] { 0x010, 0x842, 0x422, 0x281, 0x212, 0x842, 0x141, 0x123, 0x212, 0x281 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x870 */ new int[] { 0x010, 0x870, 0x871, 0x870, 0x871, 0x290, 0x870, 0x871, 0x870, 0x871, 0x290, 0x870, 0x871, 0x870, 0x871, 0x290 }
    , /* 0x871 */ new int[] { 0x010, 0x870, 0x871, 0x870, 0x871, 0x290, 0x870, 0x871, 0x870, 0x871, 0x290, 0x870, 0x871, 0x870, 0x871, 0x290 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x880 */ new int[] { 0x010, 0x880, 0x881, 0x440, 0x441, 0x880, 0x881, 0x221, 0x880, 0x881, 0x440, 0x441, 0x880, 0x881, 0x110, 0x880, 0x881 }
    , /* 0x881 */ new int[] { 0x010, 0x880, 0x881, 0x440, 0x441, 0x880, 0x881, 0x221, 0x880, 0x881, 0x440, 0x441, 0x880, 0x881, 0x110, 0x880, 0x881 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x920 */ new int[] { 0x010, 0x920, 0x921, 0x460, 0x461, 0x920, 0x921, 0x230, 0x231, 0x920, 0x921, 0x460, 0x461, 0x920, 0x921, 0x230, 0x231, 0x920, 0x921 }
    , /* 0x921 */ new int[] { 0x010, 0x920, 0x921, 0x460, 0x461, 0x920, 0x921, 0x230, 0x231, 0x920, 0x921, 0x460, 0x461, 0x920, 0x921, 0x230, 0x231, 0x920, 0x921 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x930 */ new int[] { 0x010, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311 }
    , /* 0x931 */ new int[] { 0x010, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311, 0x930, 0x931, 0x930, 0x931, 0x310, 0x311 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x940 */ new int[] { 0x010, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941 }
    , /* 0x941 */ new int[] { 0x010, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941, 0x470, 0x471, 0x940, 0x941 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x950 */ new int[] { 0x010, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x190, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951 }
    , /* 0x951 */ new int[] { 0x010, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x190, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951, 0x950, 0x951 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xa40 */ new int[] { 0x010, 0xa40, 0xa41, 0x520, 0xa40, 0xa41, 0x260, 0xa40, 0xa41, 0x520, 0xa40, 0xa41, 0x130, 0xa40, 0xa41 }
    , /* 0xa41 */ new int[] { 0x010, 0xa40, 0xa41, 0x520, 0xa40, 0xa41, 0x260, 0xa40, 0xa41, 0x520, 0xa40, 0xa41, 0x130, 0xa40, 0xa41 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xa50 */ new int[] { 0x010, 0xa50, 0xa50, 0x350, 0xa50, 0x210, 0x350, 0x150, 0xa50, 0x350 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xb00 */ new int[] { 0x010, 0xb00, 0x550, 0xb00, 0x550, 0x220, 0x550, 0xb00, 0x550, 0xb00 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xb90 */ new int[] { 0x010, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0x170, 0xb90, 0xb91, 0xb90, 0xb91 }
    , /* 0xb91 */ new int[] { 0x010, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0xb90, 0xb91, 0x170, 0xb90, 0xb91, 0xb90, 0xb91 }
    , /* 0xb92 */ new int[] { 0xb92 }
    }; // sClassPowers
    
  /** Boot coefficients */
  private static final long[][] sBootCoeffs = new long[][] 
    { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x010 */ new long[] { 0, 196884, 21493760L, 864299970L, 20245856256L, 333202640600L }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x020 */ new long[] { 0, 4372, 96256, 1240002L, 10698752L, 74428120L }
    , /* 0x021 */ new long[] { 0, 276, -2048, 11202, -49152, 184024 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x030 */ new long[] { 0, 783, 8672, 65367, 371520, 1741655 }
    , /* 0x031 */ new long[] { 0, 54, -76, -243, 1188, -1384 }
    , /* 0x032 */ new long[] { 0, 0, 248, 0, 0, 4124 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x040 */ new long[] { 0, 276, 2048, 11202, 49152, 184024 }
    , /* 0x041 */ new long[] { 0, 52, 0, 834, 0, 4760 }
    , /* 0x042 */ new long[] { 0, 20, 0, -62, 0, 216 }
    , /* 0x043 */ new long[] { 0, -12, 0, 66, 0, -232 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x050 */ new long[] { 0, 134, 760, 3345, 12256, 39350 }
    , /* 0x051 */ new long[] { 0, 9, 10, -30, 6, -25 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x060 */ new long[] { 0, 79, 352, 1431, 4160, 13015 }
    , /* 0x061 */ new long[] { 0, 78, 364, 1365, 4380, 12520 }
    , /* 0x062 */ new long[] { 0, 15, -32, 87, -192, 343 }
    , /* 0x063 */ new long[] { 0, -2, 28, -27, -52, 136 }
    , /* 0x064 */ new long[] { 0, 6, 4, -3, -12, -8 }
    , /* 0x065 */ new long[] { 0, 0, -8, 0, 0, 28 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x070 */ new long[] { 0, 51, 204, 681, 1956, 5135 }
    , /* 0x071 */ new long[] { 0, 2, 8, -5, -4, -10 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x080 */ new long[] { 0, 36, 128, 386, 1024, 2488 }
    , /* 0x081 */ new long[] { 0, 12, 0, 66, 0, 232 }
    , /* 0x082 */ new long[] { 0, 0, 0, 26, 0, 0 }
    , /* 0x083 */ new long[] { 0, -4, 0, 2, 0, 8 }
    , /* 0x084 */ new long[] { 0, 4, 0, 2, 0, -8 }
    , /* 0x085 */ new long[] { 0, 0, 0, -6, 0, 0 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x090 */ new long[] { 0, 27, 86, 243, 594, 1370 }
    , /* 0x091 */ new long[] { 0, 0, 5, 0, 0, -7 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x100 */ new long[] { 0, 22, 56, 177, 352, 870 }
    , /* 0x101 */ new long[] { 0, 6, -8, 17, -32, 54 }
    , /* 0x102 */ new long[] { 0, -3, 6, 2, 2, -5 }
    , /* 0x103 */ new long[] { 0, 21, 62, 162, 378, 819 }
    , /* 0x104 */ new long[] { 0, 1, 2, 2, -2, -1 }, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x110 */ new long[] { 0, 17, 46, 116, 252, 533 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x120 */ new long[] { 0, 15, 32, 87, 192, 343 }
    , /* 0x121 */ new long[] { 0, 6, -4, -3, 12, -8 }
    , /* 0x122 */ new long[] { 0, 7, 0, 15, 0, 71 }
    , /* 0x123 */ new long[] { 0, 0, 8, 0, 0, 28 }
    , /* 0x124 */ new long[] { 0, -1, 0, 7, 0, -9 }
    , /* 0x125 */ new long[] { 0, 6, 0, 21, 0, 56 }
    , /* 0x126 */ new long[] { 0, -2, 0, -3, 0, 8 }
    , /* 0x127 */ new long[] { 0, 14, 36, 85, 180, 360 }
    , /* 0x128 */ new long[] { 0, 2, 0, 1, 0, 0 }
    , /* 0x129 */ new long[] { 0, 0, 0, 0, 0, -4 }, null, null, null, null, null, null
    , /* 0x130 */ new long[] { 0, 12, 28, 66, 132, 258 }
    , /* 0x131 */ new long[] { 0, -1, 2, 1, 2, -2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x140 */ new long[] { 0, 11, 20, 57, 92, 207 }
    , /* 0x141 */ new long[] { 0, 3, -4, 9, -12, 15 }
    , /* 0x142 */ new long[] { 0, 10, 24, 51, 100, 190 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x150 */ new long[] { 0, 8, 22, 42, 70, 155 }
    , /* 0x151 */ new long[] { 0, -1, 4, -3, -2, 11 }
    , /* 0x152 */ new long[] { 0, 9, 19, 42, 78, 146 }
    , /* 0x153 */ new long[] { 0, 0, -2, 0, 0, -1 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x160 */ new long[] { 0, 4, 0, 10, 0, 24 }
    , /* 0x161 */ new long[] { 0, 0, 0, 2, 0, 0 }
    , /* 0x162 */ new long[] { 0, 8, 16, 34, 64, 112 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x170 */ new long[] { 0, 7, 14, 29, 50, 92 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x180 */ new long[] { 0, -2, 1, 0, 2, 1 }
    , /* 0x181 */ new long[] { 0, 7, 10, 27, 38, 82 }
    , /* 0x182 */ new long[] { 0, 3, -2, 3, -6, 10 }
    , /* 0x183 */ new long[] { 0, 0, 1, 0, 0, 1 }
    , /* 0x184 */ new long[] { 0, 6, 13, 24, 42, 73 }, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x190 */ new long[] { 0, 6, 10, 21, 36, 61 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x200 */ new long[] { 0, 6, 8, 17, 32, 54 }
    , /* 0x201 */ new long[] { 0, 2, 0, 9, 0, 10 }
    , /* 0x202 */ new long[] { 0, 1, -2, 2, 2, -1 }
    , /* 0x203 */ new long[] { 0, -2, 0, 1, 0, -2 }
    , /* 0x204 */ new long[] { 0, 3, 0, 6, 0, 13 }
    , /* 0x205 */ new long[] { 0, 5, 10, 18, 30, 51 }, null, null, null, null, null, null, null, null, null, null
    , /* 0x210 */ new long[] { 0, 6, 6, 15, 30, 41 }
    , /* 0x211 */ new long[] { 0, -1, -1, 1, 2, -1 }
    , /* 0x212 */ new long[] { 0, 0, 3, 0, 0, 8 }
    , /* 0x213 */ new long[] { 0, 5, 8, 16, 26, 44 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x220 */ new long[] { 0, 5, 6, 16, 20, 41 }
    , /* 0x221 */ new long[] { 0, 1, -2, 4, -4, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x230 */ new long[] { 0, 4, 7, 13, 19, 33 }
    , /* 0x231 */ new long[] { 0, 4, 7, 13, 19, 33 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x240 */ new long[] { 0, 3, 0, 3, 0, 7 }
    , /* 0x241 */ new long[] { 0, 3, 8, 11, 16, 31 }
    , /* 0x242 */ new long[] { 0, 0, 2, -1, -2, 4 }
    , /* 0x243 */ new long[] { 0, -1, 0, -1, 0, -1 }
    , /* 0x244 */ new long[] { 0, 0, 0, 0, 0, 4 }
    , /* 0x245 */ new long[] { 0, 0, 0, 3, 0, 0 }
    , /* 0x246 */ new long[] { 0, 0, 0, -1, 0, 0 }
    , /* 0x247 */ new long[] { 0, 2, 0, 5, 0, 8 }
    , /* 0x248 */ new long[] { 0, 4, 6, 11, 18, 28 }
    , /* 0x249 */ new long[] { 0, 0, 0, 0, 0, 0 }, null, null, null, null, null, null
    , /* 0x250 */ new long[] { 0, 4, 5, 10, 16, 25 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x260 */ new long[] { 0, 4, 4, 10, 12, 26 }
    , /* 0x261 */ new long[] { 0, 3, 6, 9, 14, 22 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x270 */ new long[] { 0, 3, 5, 9, 12, 20 }
    , /* 0x271 */ new long[] { 0, 3, 5, 9, 12, 20 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x280 */ new long[] { 0, 3, 0, 1, 0, 7 }
    , /* 0x281 */ new long[] { 0, 3, 4, 9, 12, 15 }
    , /* 0x282 */ new long[] { 0, -1, 0, 1, 0, -1 }
    , /* 0x283 */ new long[] { 0, 2, 0, 3, 0, 6 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x290 */ new long[] { 0, 3, 4, 7, 10, 17 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x300 */ new long[] { 0, 3, -1, 0, 0, 0 }
    , /* 0x301 */ new long[] { 0, 4, 2, 6, 10, 15 }
    , /* 0x302 */ new long[] { 0, 0, -2, 2, -2, 3 }
    , /* 0x303 */ new long[] { 0, 3, 4, 5, 10, 15 }
    , /* 0x304 */ new long[] { 0, 0, 2, 0, 0, 3 }
    , /* 0x305 */ new long[] { 0, 3, 3, 8, 8, 16 }
    , /* 0x306 */ new long[] { 0, 1, -1, 2, -2, 2 }, null, null, null, null, null, null, null, null, null
    , /* 0x310 */ new long[] { 0, 3, 3, 6, 9, 13 }
    , /* 0x311 */ new long[] { 0, 3, 3, 6, 9, 13 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x320 */ new long[] { 0, 2, 4, 6, 8, 12 }
    , /* 0x321 */ new long[] { 0, 2, 0, 2, 0, 4 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x330 */ new long[] { 0, -1, 1, -1, 0, 2 }
    , /* 0x331 */ new long[] { 0, 2, 4, 5, 6, 14 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x340 */ new long[] { 0, 3, 2, 5, 6, 12 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x350 */ new long[] { 0, 1, 4, 6, 6, 10 }
    , /* 0x351 */ new long[] { 0, 2, 3, 5, 6, 10 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x360 */ new long[] { 0, 3, 2, 3, 6, 10 }
    , /* 0x361 */ new long[] { 0, 0, -1, 0, 0, 1 }
    , /* 0x362 */ new long[] { 0, 1, 0, 3, 0, 2 }
    , /* 0x363 */ new long[] { 0, 2, 3, 4, 6, 9 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x380 */ new long[] { 0, 2, 2, 5, 4, 9 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x390 */ new long[] { 0, 3, 1, 3, 6, 6 }
    , /* 0x391 */ new long[] { 0, 0, 1, 0, 0, 3 }
    , /* 0x392 */ new long[] { 0, 2, 2, 4, 5, 7 }
    , /* 0x393 */ new long[] { 0, 2, 2, 4, 5, 7 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x400 */ new long[] { 0, 0, 0, 1, 0, 0 }
    , /* 0x401 */ new long[] { 0, 2, 0, 1, 0, 2 }
    , /* 0x402 */ new long[] { 0, 1, 0, 2, 0, 3 }
    , /* 0x403 */ new long[] { 0, 1, 0, 2, 0, 3 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x410 */ new long[] { 0, 2, 2, 3, 4, 7 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x420 */ new long[] { 0, 2, 2, 3, 2, 9 }
    , /* 0x421 */ new long[] { 0, 1, 0, 0, -2, 4 }
    , /* 0x422 */ new long[] { 0, 0, -1, 0, 0, 0 }
    , /* 0x423 */ new long[] { 0, 1, 3, 3, 4, 7 }, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x440 */ new long[] { 0, 1, 2, 4, 4, 5 }
    , /* 0x441 */ new long[] { 0, 1, 2, 4, 4, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x450 */ new long[] { 0, 2, 1, 3, 4, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x460 */ new long[] { 0, 0, -1, 1, -1, 1 }
    , /* 0x461 */ new long[] { 0, 0, -1, 1, -1, 1 }
    , /* 0x462 */ new long[] { 0, 2, 1, 3, 3, 5 }
    , /* 0x463 */ new long[] { 0, 2, 1, 3, 3, 5 }, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x470 */ new long[] { 0, 1, 2, 3, 3, 5 }
    , /* 0x471 */ new long[] { 0, 1, 2, 3, 3, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x480 */ new long[] { 0, 1, 0, 1, 0, 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x500 */ new long[] { 0, 2, 1, 2, 2, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x510 */ new long[] { 0, 1, 2, 2, 2, 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x520 */ new long[] { 0, 0, 0, 2, 0, 2 }
    , /* 0x521 */ new long[] { 0, 1, 0, 1, 0, 2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x540 */ new long[] { 0, 1, 1, 3, 2, 4 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x550 */ new long[] { 0, 2, 1, 1, 2, 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x560 */ new long[] { 0, 1, 2, 1, 2, 3 }
    , /* 0x561 */ new long[] { 0, 0, 0, 1, 0, 0 }
    , /* 0x562 */ new long[] { 0, 0, 0, 1, 0, 0 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x570 */ new long[] { 0, 0, 1, 0, 0, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x590 */ new long[] { 0, 1, 1, 2, 2, 3 }
    , /* 0x591 */ new long[] { 0, 1, 1, 2, 2, 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x600 */ new long[] { 0, 2, 0, 0, 0, 1 }
    , /* 0x601 */ new long[] { 0, 0, 2, 2, 2, 3 }
    , /* 0x602 */ new long[] { 0, 1, 1, 2, 2, 2 }
    , /* 0x603 */ new long[] { 0, -1, 1, 0, 0, 0 }
    , /* 0x604 */ new long[] { 0, 1, 0, 1, 0, 1 }
    , /* 0x605 */ new long[] { 0, 0, 0, 0, 0, 1 }, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x620 */ new long[] { 0, 1, 1, 2, 1, 3 }
    , /* 0x621 */ new long[] { 0, 1, 1, 2, 1, 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x660 */ new long[] { 0, 2, 0, 1, 2, 2 }
    , /* 0x661 */ new long[] { 0, 1, 1, 1, 2, 2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x680 */ new long[] { 0, 1, 0, 1, 0, 0 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x690 */ new long[] { 0, 1, 1, 1, 1, 3 }
    , /* 0x691 */ new long[] { 0, 1, 1, 1, 1, 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x700 */ new long[] { 0, 1, 0, 2, 2, 2 }
    , /* 0x701 */ new long[] { 0, 0, -1, 1, 0, 0 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x710 */ new long[] { 0, 1, 1, 1, 1, 2 }
    , /* 0x711 */ new long[] { 0, 1, 1, 1, 1, 2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x780 */ new long[] { 0, 1, 1, 1, 0, 2 }
    , /* 0x781 */ new long[] { 0, 0, 0, 0, -1, 1 }
    , /* 0x782 */ new long[] { 0, 0, 0, 0, -1, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x840 */ new long[] { 0, 0, 0, 1, 0, 1 }
    , /* 0x841 */ new long[] { 0, -1, 0, 0, 0, 0 }
    , /* 0x842 */ new long[] { 0, 0, 1, 0, 0, 0 }, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x870 */ new long[] { 0, 0, 1, 1, 1, 2 }
    , /* 0x871 */ new long[] { 0, 0, 1, 1, 1, 2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x880 */ new long[] { 0, 1, 0, 0, 0, 1 }
    , /* 0x881 */ new long[] { 0, 1, 0, 0, 0, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x920 */ new long[] { 0, 0, 1, 1, 1, 1 }
    , /* 0x921 */ new long[] { 0, 0, 1, 1, 1, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x930 */ new long[] { 0, 0, 0, 0, 0, 1 }
    , /* 0x931 */ new long[] { 0, 0, 0, 0, 0, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x940 */ new long[] { 0, 1, 0, 1, 1, 1 }
    , /* 0x941 */ new long[] { 0, 1, 0, 1, 1, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0x950 */ new long[] { 0, 1, 0, 1, 1, 1 }
    , /* 0x951 */ new long[] { 0, 1, 0, 1, 1, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xa40 */ new long[] { 0, 0, 0, 0, 0, 0 }
    , /* 0xa41 */ new long[] { 0, 0, 0, 0, 0, 0 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xa50 */ new long[] { 0, 1, 1, 0, 0, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xb00 */ new long[] { 0, 0, 1, 1, 0, 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    , /* 0xb90 */ new long[] { 0, 0, 0, 1, 1, 1 }
    , /* 0xb91 */ new long[] { 0, 0, 0, 1, 1, 1 }
    , /* 0xb92 */ new long[] { 29061947 }
    }; // sBootCoeffs

  /**
   * Test method
   */
  public static void main(String[] args) {
    System.out.println("last valid class code: " + String.format("0x%03x", sValidClasses[sValidClasses.length - 1]));
    final int[] lastPow = sClassPowers[sClassPowers.length - 1];
    System.out.println("last class power:      " + String.format("%d", lastPow[0] ) + " @" + String.format("0x%x", sClassPowers.length - 1));
    final long[] lastBoot = sBootCoeffs[sBootCoeffs.length - 1];
    System.out.println("last boot coefficent:  " + String.format("%d", lastBoot[0]) + " @" + String.format("0x%x", sBootCoeffs .length - 1));
  } // main
  
} // McKayThompsonTables
