mv -v cfp.jpat        cfsper.jpat       
mv -v cfpcount.jpat   cfsperno.jpat  
mv -v cfpleast.jpat   cfspermin.jpat  
mv -v cfplen.jpat     cfsperlen.jpat    
mv -v cfplenmult.jpat cfsperlemul.jpat
mv -v cfpmid0.jpat    cfspercent0.jpat   
mv -v cfpmid1.jpat    cfspercent1.jpat   
mv -v cfpmidpar.jpat  void.jpat 
mv -v cfpn.jpat       cfspertin.jpat      
mv -v cfs.jpat        cfsqrt.jpat       
mv -v cfsden.jpat     cfsqden.jpat    
mv -v cfsnum.jpat     cfsqnum.jpat    
