#!perl

# Extract "unsigned version (is|of) ... " relations
# @(#) $Id$
# 2021-11-01, Georg Fischer
#
#:# Usage:
#:#   perl unsigned.pl [-d debug] jcat25.txt > outfile
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);
print "# generated by internal/fischer/unsigned.pl at $timestamp\n";

my $debug = 0;
my $mode = "r"; # row sums
my $callcode = "unsigned";
my $offset = 0;
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt   =~ m{d}) {
        $debug      = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

while (<>) {
    s/\s+\Z//; # chompr
    m{^\S+\s(\S+)\s(.*)};
    my ($aseqno, $name) = ($1, $2);
    my $rseqno = "";
    if ($name =~ m{unsigned}i) {
        if (0) {
        } elsif ($name =~ m{(A\d+) *\(unsigned}) {
            $rseqno = $1;
        } elsif ($name =~ m{(A\d+) +is (the|an) unsigned}) {
            $rseqno = $1;
        } elsif ($name =~ m{[Uu]nsigned (version|triangle)[^A]*(A\d+)}) {
            $rseqno = $2;
        } else {
            print STDERR join("\t", $aseqno, $name) . "\n";
        }
        if ($rseqno ne "") {
            print join("\t", $aseqno, $callcode, 0, $rseqno, $name) . "\n";
        } 
    }
} # while <>
#--------------------------------------------
__DATA__
A028338 is unsigned version
%Y A234937 A210590 is the unsigned version.