package irvine.oeis.a035;
// Generated by gen_seq4.pl genet at 2020-12-12 21:47
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A035457 Number of partitions of n into parts of the form 4*k + 2.
 * G.f.: Product_{k>=0} (1/(1-x^(4*k+2)))
 * @author Georg Fischer
 */
public class A035457 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A035457() {
    super(0, 0);
    mNextH = advanceH(0);
  }

  @Override
  protected Z[] advanceF(final int k) {
    return new Z[] { Z.ONE };
  }

  @Override
  protected Z advanceG(final int k) {
    return Z.ONE;
  }

  @Override
  protected Z advanceH(final int k) {
    return Z.valueOf(4*k+2);
  }

}
