package irvine.oeis.a050;
// Generated by gen_seq4.pl parm2 at 2021-08-06 13:56

/**
 * A050090 Numbers k such that A050088(k) &lt; A050088(k+1).
 * @author Georg Fischer
 */
public class A050090 extends A050002 {

  /** Construct the sequence. */
  public A050090() {
    super(new A050088());
  }
}
