package irvine.oeis.a050;
// manually 2021-08-20

import irvine.math.z.Z;
import irvine.oeis.Subsequence;
import irvine.oeis.a006.A006161;

/**
 * A050825 Even numbers in the sequence generated by a(n)=a(a(n-1)-1)+a(n+1-a(n-1)).
 * @author Georg Fischer
 */
public class A050825 extends Subsequence {

  /** Construct the sequence */
  public A050825 () {
    super(new A006161());
  }

  @Override
  public boolean isOk(final Z term) {
    return term.isEven();
  }

}
