package irvine.oeis.a050;
// Generated by gen_seq4.pl parm2 at 2021-08-06 13:56

/**
 * A050015 Numbers k such that A050012(k) &gt; A050012(k+1).
 * @author Georg Fischer
 */
public class A050015 extends A050003 {

  /** Construct the sequence. */
  public A050015() {
    super(new A050012());
  }
}
