package irvine.oeis.a062;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.prime.PrimePositionSubsequence;


/**
 * A062654 Numbers k such that 88^k - 87^k is prime or a strong pseudoprime.
 * @author Georg Fischer
 */
public class A062654 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A062654() {
    super("[[0],[-7832],[177],[-1]]", "[0, 1]", 0);
  }
}
