package irvine.oeis.a065;
// Generated by gen_seq4.pl amoda

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a000.A000720;
import irvine.oeis.a002.A002808;
import irvine.oeis.Sequence2;

/**
 * A065861 Remainder when the n-th composite number is divided by pi(n), the number of primes not exceeding n.
 * @author Georg Fischer
 */
public class A065861 extends Sequence2 {

  private A002808 mSeq1 = new A002808();
  private A000720 mSeq2 = new A000720();

  public A065861() {
    mSeq1.next();
    mSeq2.next();
  }

  @Override
  public Z next() {
    return mSeq1.next().mod(mSeq2.next());
  }
}

