package irvine.oeis.a067;
// Generated by gen_seq4.pl n2 at 2022-12-15 22:30

import irvine.math.z.Z;
import irvine.oeis.a067.A067297;

/**
 * A067320 Even-indexed members of A067297.
 * @author Georg Fischer
 */
public class A067320 extends A067297 {

  @Override
  public Z next() {
    final Z result = super.next();
    super.next();
    return result;
  }
}
