package irvine.oeis.a111;
// Generated by gen_seq4.pl geneth at 2020-12-15 15:48
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;
import irvine.oeis.a000.A000203;

/**
 * A111865 Expansion of g.f. Product_{k>=1} 1/(1-x^sigma(k)).
 * @author Georg Fischer
 */
public class A111865 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A111865() {
    super(0, 1);
    mSeqH = new A000203();
  /*
    mNextH = advanceH(mKh);
    mNextH = advanceH(mKh);
  */
  }

  @Override
  protected Z[] advanceF(final long k) {
    return new Z[] { Z.ONE };
  }

  @Override
  protected Z advanceG(final long k) {
    return Z.ONE;
  }

  @Override
  protected Z advanceH(final long k) {
    return mSeqH.next();
  }

}