package irvine.oeis.a127;
// Generated by gen_seq4.pl triprod at 2023-05-30 18:09

import irvine.oeis.a002.A002260;
import irvine.oeis.a007.A007318;
import irvine.oeis.triangle.Product;

/**
 * A127717 Triangle read by rows. T(n, k) = k * binomial(n + 1, k + 1), for 1 &lt;= k &lt;= n.
 * @author Georg Fischer
 */
public class A127717 extends Product {

  /** Construct the sequence. */
  public A127717() {
    super(1, new A002260(), new A007318());
  }
}
