package irvine.oeis.a128;
// Generated by gen_seq4.pl convprom/convprod at 2023-02-25 22:00

import irvine.oeis.a000.A000012;
import irvine.oeis.a000.A000594;
import irvine.oeis.transform.ConvolutionProduct;

/**
 * A128379 A000012^23 * A000594.
 * @author Georg Fischer
 */
public class A128379 extends ConvolutionProduct {

  /** Construct the sequence. */
  public A128379() {
    super(1, "23,1", new A000012(),new A000594());
  }
}
