package irvine.oeis.a128;
// Generated by gen_seq4.pl convprom/convprod at 2023-02-25 22:00

import irvine.oeis.a000.A000012;
import irvine.oeis.a000.A000594;
import irvine.oeis.transform.ConvolutionProduct;

/**
 * A128378 Partial sums of A128379.
 * @author Georg Fischer
 */
public class A128378 extends ConvolutionProduct {

  /** Construct the sequence. */
  public A128378() {
    super(1, "24,1", new A000012(),new A000594());
  }
}
