package irvine.oeis.a130;
// Generated by gen_seq4.pl trixint0/parmof2 at 2023-06-27 10:07

import irvine.oeis.a130.A130159;
import irvine.oeis.a130.A130162;

/**
 * A130160 A051731 * A130159 as a diagonalized matrix.
 * @author Georg Fischer
 */
public class A130160 extends A130162 {

  /** Construct the sequence. */
  public A130160() {
    super(1, new A130159());
  }
}
