package irvine.oeis.a147;
// Generated by gen_seq4.pl genet at 2020-12-09 23:20
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.a005.A005185;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A147879 Expansion of Product_{k>=1} (1 + x^k*A005185(k)).
 * @author Georg Fischer
 */
public class A147879 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A147879() {
    super(0, 1);
    mSeqG = new A005185();
  }

  @Override
  protected Z advanceF(final int k) {
    return Z.NEG_ONE;
  }

  @Override
  protected Z advanceG(final int k) {
    return mSeqG.next().negate();
  }

  @Override
  protected Z advanceH(final int k) {
    return Z.valueOf(k);
  }

}