package irvine.oeis.a151;
// Generated by gen_seq4.pl genet at 2020-12-09 18:17
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A151671 G.f.: Prod_{k >= 0} (1+3*x^(5^k)).
 * @author Georg Fischer
 */
public class A151671 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A151671() {
    super(0, 0);
    mKh = 0;
    mNextH = Z.ZERO; // for a^k in advanceH(mKh)
  }

  @Override
  protected Z advanceF(final int k) {
    return Z.NEG_ONE;
  }

  @Override
  protected Z advanceG(final int k) {
    return Z.THREE.negate();
  }

  @Override
  protected Z advanceH(final int k) {
    return Z.FIVE.pow(k);
  }

}