package irvine.oeis.a155;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-25 19:48

import irvine.oeis.a155.A155013;

/**
 * A155018 Integer part of square root of n^15 = A010803(n).
 * @author Georg Fischer
 */
public class A155018 extends A155013 {

  /** Construct the sequence. */
  public A155018() {
    super(0, 15);
  }
}
