package irvine.oeis.a155;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-25 19:48

import irvine.oeis.a155.A155013;

/**
 * A155015 Integer part of square root of n^11 = A008455(n).
 * @author Georg Fischer
 */
public class A155015 extends A155013 {

  /** Construct the sequence. */
  public A155015() {
    super(0, 11);
  }
}
