package irvine.oeis.a155;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-25 19:48

import irvine.oeis.a155.A155013;

/**
 * A155016 Integer part of square root of A010801.
 * @author Georg Fischer
 */
public class A155016 extends A155013 {

  /** Construct the sequence. */
  public A155016() {
    super(0, 13);
  }
}
