package irvine.oeis.a159;
// Generated by gen_seq4.pl dirichcon2 at 2021-04-22 20:53

import irvine.math.z.Z;
import irvine.oeis.DirichletConvolutionSequence;
import irvine.oeis.a007.A007247;
import irvine.oeis.a029.A029937;

/**
 * A159046 Dimension of the space of newforms of weight 2 on the subgroup Gamma_1(n).
 * @author Georg Fischer
 */
public class A159046 extends DirichletConvolutionSequence {

  /** Construct the sequence. */
  public A159046() {
    super(new A007247(), 0, new A029937(), 1);
  }

  @Override
  public Z next() {
    return super.next().divide(52);
  }

}