package irvine.oeis.a167;
// Generated by gen_seq4.pl convprom/convprod at 2023-02-25 22:00

import irvine.oeis.a000.A000108;
import irvine.oeis.a122.A122803;
import irvine.oeis.transform.ConvolutionProduct;

/**
 * A167479 Convolution of the Catalan numbers A000108(n) and (-2)^n.
 * @author Georg Fischer
 */
public class A167479 extends ConvolutionProduct {

  /** Construct the sequence. */
  public A167479() {
    super(0, "1,1", new A000108(),new A122803());
  }
}
