package irvine.oeis.a185;
// Generated by gen_seq4.pl genet at 2020-12-09 22:12
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A185325 Number of partitions of n into parts >= 5.
 * Prod_{k>=5} 1/(1-x^k)
 * @author Georg Fischer
 */
public class A185325 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A185325() {
    super(0, 0);
    mKh = 1;
    mNextH = Z.ONE; // for a^k in advanceH(mKh)

  }

  @Override
  protected Z advanceF(final int k) {
    return Z.ONE;
  }

  @Override
  protected Z advanceG(final int k) {
    return (mK < 5) ? Z.ZERO : Z.ONE;
  }

  @Override
  protected Z advanceH(final int k) {
    return Z.valueOf(k);
  }

}