package irvine.oeis.a201;
// Generated by gen_seq4.pl decsolvr at 2021-08-02 11:09

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A201575 Decimal expansion of greatest x satisfying x^2 + 7 = csc(x) and 0 < x < Pi.
 * Equation; x^2+7-csc(x)
 * @author Georg Fischer
 */
public class A201575 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence */
  public A201575() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return x.pow(2).add(CR.SEVEN).subtract(REALS.csc(x));
      }
    }.inverseMonotone(CR.valueOf(3.0), CR.valueOf(3.1)).execute(CR.ZERO));
  }
}
