package irvine.oeis.a202;
// Generated by gen_seq4.pl decsolv at 2021-08-02 13:55

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A202351 Decimal expansion of least x satisfying 3*x = exp(x).
 * Equation; 3*x-exp(x)
 * @author Georg Fischer
 */
public class A202351 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A202351() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return CR.THREE.multiply(x).subtract(x.exp());
      }
    }.inverseMonotone(CR.valueOf(0.6), CR.valueOf(0.7)).execute(CR.ZERO));
  }
}
