package irvine.oeis.a204;
// Generated by gen_seq4.pl dersimple at 2022-12-15 23:30

import irvine.math.z.Z;
import irvine.oeis.a204.A204321;

/**
 * A204687 a(n) = A204321(n)/4.
 * @author Georg Fischer
 */
public class A204687 extends A204321 {

  @Override
  public Z next() {
    return super.next().divide(4);
  }
}
