package irvine.oeis.a238;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-26 12:00

import irvine.oeis.a155.A155013;

/**
 * A238170 Integer part of square root of A001017: a(n) = floor(n^(9/2)).
 * @author Georg Fischer
 */
public class A238170 extends A155013 {

  /** Construct the sequence. */
  public A238170() {
    super(0, 9);
  }
}
