package irvine.oeis.a242;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-26 12:00

import irvine.oeis.a155.A155013;

/**
 * A242038 Integer part of square root of A010809(n) = n^21.
 * @author Georg Fischer
 */
public class A242038 extends A155013 {

  /** Construct the sequence. */
  public A242038() {
    super(0, 21);
  }
}
