package irvine.oeis.a247;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-26 12:00

import irvine.oeis.a155.A155013;

/**
 * A247894 Integer part of square root of A010807: a(n) = floor(sqrt(n^19)).
 * @author Georg Fischer
 */
public class A247894 extends A155013 {

  /** Construct the sequence. */
  public A247894() {
    super(0, 19);
  }
}
