package irvine.oeis.a248;
// Generated by gen_seq4.pl A155013/parmof2 at 2023-02-26 12:00

import irvine.oeis.a155.A155013;

/**
 * A248109 Integer part of square root of A010811(n) = n^23.
 * @author Georg Fischer
 */
public class A248109 extends A155013 {

  /** Construct the sequence. */
  public A248109() {
    super(0, 23);
  }
}
