package irvine.oeis.a262;
// Generated by gen_seq4.pl genet at 2020-12-09 23:20
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A262877 Expansion of Product_{k>=1} 1/(1-x^(3k-2))^k.
 * @author Georg Fischer
 */
public class A262877 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A262877() {
    super(0, 1);
  }

  @Override
  protected Z[] advanceF(final int k) {
    return new Z[] { Z.ONE };
  }

  @Override
  protected Z advanceG(final int k) {
    return Z.ONE;
  }

  @Override
  protected Z advanceH(final int k) {
    return Z.valueOf(3*k-2);
  }

}