package irvine.oeis.a265;
// Generated by gen_seq4.pl geneth at 2020-12-15 15:33
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;

/**
 * A265821 Expansion of Product_{k>=1} 1/(1 - (3*k-2)*x^(3*k-2)).
 * @author Georg Fischer
 */
public class A265821 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A265821() {
    super(0, 1);
    mNextH = advanceH(mKh);
  }

  @Override
  protected Z[] advanceF(final long k) {
    return new Z[] { Z.ONE };
  }

  @Override
  protected Z advanceG(final long k) {
    return Z.valueOf((3L*mKh-2L));
  }

  @Override
  protected Z advanceH(final long k) {
    return Z.valueOf((3*k-2));
  }

}