package irvine.oeis.a284;
// Generated by gen_seq4.pl A284150/parmof3 at 2023-04-03 11:26

import irvine.oeis.a284.A284150;

/**
 * A284151 Sum_{d|n, d=1 or 6 mod 7} d.
 * @author Georg Fischer
 */
public class A284151 extends A284150 {

  /** Construct the sequence. */
  public A284151() {
    super(1, 7, 1,6);
  }
}
