package irvine.oeis.a323;
// Generated by gen_seq4.pl knest/jaguarz at 2023-03-01 20:54

import irvine.factor.factor.Jaguar;
import irvine.math.z.Z;
import irvine.oeis.a001.A001142;

/**
 * A323444 Sum of exponents in prime-power factorization of Product_{k=0..n} binomial(n,k) (A001142).
 * @author Georg Fischer
 */
public class A323444 extends A001142 {
  @Override
  public Z next() {
    return Z.valueOf(Jaguar.factor(super.next()).bigOmega());
  }
}
