package irvine.oeis.a341;
// Generated by gen_seq4.pl decexp at 2021-07-18 19:09

import irvine.math.cr.CR;
import irvine.math.cr.Zeta;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A341901 Decimal expansion of 1/zeta(9).
 * Formula: 1/zeta(9)
 * @author Georg Fischer
 */
public class A341901 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A341901() {
    super(0, CR.ONE.divide(Zeta.zeta(9)));
  }
}
