package irvine.oeis.a357;
// Generated by gen_seq4.pl greprec3/holos at 2023-05-08 15:06

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A357711 Expansion of e.g.f. cosh( 2 * log(1-x) ).
 * @author Georg Fischer
 */
public class A357711 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A357711() {
    super(0, "[[0],[-1,-1],[1]]", "1,0,4,12,60,360,2520", 0);
  }
}
