package irvine.oeis.a358;
// Generated by gen_seq4.pl binomin/holos at 2023-05-08 14:44

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A358620 Number of nonzero digits needed to write all nonnegative n-digit integers.
 * @author Georg Fischer
 */
public class A358620 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A358620() {
    super(1, "[[0],[-10,-90],[-8,9]]", "[9,171]", 0);
  }
}
