package irvine.oeis.a358;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A358518 a(n) = Sum_{k=0..n} binomial(n+3*k+3,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A358518 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A358518() {
    // o.g.f. 2/(1-x)^4/(1+(1-4*x/(1-x)^4)^(1/2))
    // recurrence -(n+1)*u(n)-(-9*n+2)*u(n-1)-(14*n-8)*u(n-2)-(-10*n+20)*u(n-3)-(5*n-15)*u(n-4)-(-n+4)*u(n-5) = 0
    super(0, "[[0],[-4,1],[15,-5],[-20,10],[8,-14],[-2,9],[-1,-1]]", "[1,5,20,85,405,2116]", 0);
  }
}
