package irvine.oeis.a359;
// Generated by gen_seq4.pl binomin/holos at 2023-05-08 14:44

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A359499 a(n) = ((2*n+1)^16 - 1)/64.
 * @author Georg Fischer
 */
public class A359499 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A359499() {
    super(0, "[[0],[-1,-15,-140,-910,-4368,-16016,-45760,-102960,-183040,-256256,-279552,-232960,-143360,-61440,-16384,-2048],[-1,15,-140,910,-4368,16016,-45760,102960,-183040,256256,-279552,232960,-143360,61440,-16384,2048]]", "[0,672605,2384185791]", 0);
  }
}
