package irvine.oeis.a359;
// Generated by gen_seq4.pl binomin/holos at 2023-05-08 14:44

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A359844 a(n) = ((2*n+1)^8 + 1)/2.
 * @author Georg Fischer
 */
public class A359844 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A359844() {
    super(0, "[[0],[-1,-8,-56,-224,-560,-896,-896,-512,-128],[1,-8,56,-224,560,-896,896,-512,128]]", "[1,3281]", 0);
  }
}
