package irvine.oeis.a360;
// Generated by gen_seq4.pl binomin/holos at 2023-05-08 14:44

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360416 a(n) = 8*n^2 - 9*n + 3.
 * @author Georg Fischer
 */
public class A360416 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360416() {
    super(1, "[[0],[-3,9,-8],[20,-25,8]]", "[2,17]", 0);
  }
}
