package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360059 a(n) = Sum_{k=0..n} (-1)^k * binomial(n+3*k+3,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360059 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360059() {
    // o.g.f. 2/(1-x)^4/(1+(1+4*x/(1-x)^4)^(1/2))
    // recurrence -(n+1)*u(n)-(-n-2)*u(n-1)-(6*n-12)*u(n-2)-(-10*n+20)*u(n-3)-(5*n-15)*u(n-4)-(-n+4)*u(n-5) = 0
    super(0, "[[0],[-4,1],[15,-5],[-20,10],[12,-6],[2,1],[-1,-1]]", "[1,3,4,3,5,12]", 0);
  }
}
