package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360025 a(n) = Sum_{k=0..floor(n/3)} (-1)^k * binomial(n-2*k,k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360025 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360025() {
    // o.g.f. 2/(1-x+((1-x)^2+4*x^3*(1-x))^(1/2))
    // recurrence -(n+3)*u(n)-(-2*n-4)*u(n-1)-(n+1)*u(n-2)-(4*n-6)*u(n-3)-(-4*n+8)*u(n-4) = 0
    super(0, "[[0],[-8,4],[6,-4],[-1,-1],[4,2],[-3,-1]]", "[1,1,1,0,-1]", 0);
  }
}
