package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360050 a(n) = Sum_{k=0..floor(n/4)} (-1)^k * binomial(n+3,4*k+3) * Catalan(k).
 * @author Georg Fischer
 */
public class A360050 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360050() {
    // o.g.f. 2/(1-x)^2/((1-x)^2+((1-x)^4+4*x^4)^(1/2))
    // recurrence 5*(n+3)*n*u(n-1)+5*(n-1)*n*u(n-5)-n*(9*n-8)*u(n-4)+10*(n+1)*n*u(n-3)-10*(n+2)*n*u(n-2)-(n+4)*n*u(n) = 0
    super(0, "[[0],[0,-5,5],[0,8,-9],[0,10,10],[0,-20,-10],[0,15,5],[0,-4,-1]]", "[1,4,10,20,34,48]", 0);
  }
}
