package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360211 a(n) = Sum_{k=0..floor(n/2)} (-1)^k * binomial(2*n-3*k,n-2*k).
 * @author Georg Fischer
 */
public class A360211 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360211() {
    // o.g.f. 1/(1-4*x)^(1/2)/(1+1/2*x*(1-(1-4*x)^(1/2)))
    // recurrence -n*(9*n-13)*u(n)-(-27*(n-4)^2-159*n+408)*u(n-1)+2*(9*n-4)*(2*n-3)*u(n-2)-n*(9*n-13)*u(n-3)+2*(9*n-4)*(2*n-3)*u(n-4) = 0
    super(0, "[[0],[24,-70,36],[0,13,-9],[24,-70,36],[24,-57,27],[0,13,-9]]", "[1,2,5,17,61]", 0);
  }
}
