package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360152 a(n) = Sum_{k=0..floor(n/3)} binomial(2*n-5*k,n-3*k).
 * @author Georg Fischer
 */
public class A360152 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360152() {
    // o.g.f. 1/(1-4*x)^(1/2)/(1-1/2*x^2*(1-(1-4*x)^(1/2)))
    // recurrence -(n+5)*(31*(n-1)^2+247*n+237)*u(n+5)+2*(2*n+5)*(31*(n-1)^2+309*n+453)*u(n+4)+(n+5)*(31*(n-1)^2+247*n+237)*u(n+3)-2*(2*n+5)*(31*(n-1)^2+309*n+453)*u(n+2)-(n+5)*(31*(n-1)^2+247*n+237)*u(n)+2*(2*n+5)*(31*(n-1)^2+309*n+453)*u(n-1) = 0
    super(0, "[[0],[-240,726,-562,124],[0,-118,125,-31],[0],[240,-726,562,-124],[0,118,-125,31],[-240,726,-562,124],[0,-118,125,-31]]", "[1,2,6,21,73,262,960]", 0);
  }
}
