package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360103 a(n) = Sum_{k=0..n} binomial(n+4*k,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360103 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360103() {
    // o.g.f. 1/2*(1-x)^4*(1-(1-4*x/(1-x)^5)^(1/2))/x
    // recurrence -(n+1)*u(n)-(-10*n+6)*u(n-1)-(19*n-47)*u(n-2)-(-20*n+80)*u(n-3)-(15*n-85)*u(n-4)-(-6*n+44)*u(n-5)-(n-9)*u(n-6) = 0
    super(0, "[[0],[9,-1],[-44,6],[85,-15],[-80,20],[47,-19],[-6,10],[-1,-1]]", "[1,2,9,49,283,1715,10793]", 0);
  }
}
