package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360100 a(n) = Sum_{k=0..n} binomial(n+2*k-1,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360100 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360100() {
    // o.g.f. 1/2*(1-(1-4*x/(1-x)^3)^(1/2))/x*(1-x)^3
    // recurrence -(n+1)*u(n)-(-8*n+5)*u(n-1)-(10*n-27)*u(n-2)-(-4*n+17)*u(n-3)-(n-6)*u(n-4) = 0
    super(0, "[[0],[6,-1],[-17,4],[27,-10],[-5,8],[-1,-1]]", "[1,1,5,23,111]", 0);
  }
}
