package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360102 a(n) = Sum_{k=0..n} binomial(n+2*k,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360102 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360102() {
    // o.g.f. 1/2*(1-x)^2*(1-(1-4*x/(1-x)^3)^(1/2))/x
    // recurrence -(n+1)*u(n)-(-8*n+4)*u(n-1)-(10*n-20)*u(n-2)-(-4*n+14)*u(n-3)-(n-5)*u(n-4) = 0
    super(0, "[[0],[5,-1],[-14,4],[20,-10],[-4,8],[-1,-1]]", "[1,2,7,30,141]", 0);
  }
}
