package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360026 a(n) = Sum_{k=0..floor(n/4)} (-1)^k * binomial(n-3*k,k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360026 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360026() {
    // o.g.f. 2/(1-x+((1-x)^2+4*x^4*(1-x))^(1/2))
    // recurrence -(n+8)*u(n+4)-(-2*n-14)*u(n+3)-(n+6)*u(n+2)-(4*n+8)*u(n)-(-4*n-6)*u(n-1) = 0
    super(0, "[[0],[-10,4],[8,-4],[0],[-2,-1],[6,2],[-4,-1]]", "[1,1,1,1,0,-1]", 0);
  }
}
