package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360058 a(n) = Sum_{k=0..n} (-1)^k * binomial(n+2*k+2,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360058 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360058() {
    // o.g.f. 2/(1-x)^3/(1+(1+4*x/(1-x)^3)^(1/2))
    // recurrence -(n+1)*u(n)+2*u(n-1)-(2*n-6)*u(n-2)-(-4*n+8)*u(n-3)-(n-3)*u(n-4) = 0
    super(0, "[[0],[3,-1],[-8,4],[6,-2],[2],[-1,-1]]", "[1,2,2,2,3]", 0);
  }
}
