package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360046 a(n) = Sum_{k=0..floor(n/4)} binomial(n+3,4*k+3) * Catalan(k).
 * @author Georg Fischer
 */
public class A360046 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360046() {
    // o.g.f. 2/(1-x)^2/((1-x)^2+((1-x)^4-4*x^4)^(1/2))
    // recurrence 5*(n+3)*n*u(n-1)-3*(n-1)*n*u(n-5)-(n+8)*n*u(n-4)+10*(n+1)*n*u(n-3)-10*(n+2)*n*u(n-2)-(n+4)*n*u(n) = 0
    super(0, "[[0],[0,3,-3],[0,-8,-1],[0,10,10],[0,-20,-10],[0,15,5],[0,-4,-1]]", "[1,4,10,20,36,64]", 0);
  }
}
