package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360045 a(n) = Sum_{k=0..floor(n/3)} binomial(n+2,3*k+2) * Catalan(k).
 * @author Georg Fischer
 */
public class A360045 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360045() {
    // o.g.f. 2/(1-x)/((1-x)^2+((1-x)^4-4*x^3*(1-x))^(1/2))
    // recurrence 4*(n+2)*n*u(n-1)-5*(n-1)*n*u(n-4)+2*n*(4*n-3)*u(n-3)-6*(n+1)*n*u(n-2)-(n+3)*n*u(n) = 0
    super(0, "[[0],[0,5,-5],[0,-6,8],[0,-6,-6],[0,8,4],[0,-3,-1]]", "[1,3,6,11,21]", 0);
  }
}
