package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360027 a(n) = Sum_{k=0..floor(n/5)} (-1)^k * binomial(n-4*k,k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360027 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360027() {
    // o.g.f. 2/(1-x+((1-x)^2+4*x^5*(1-x))^(1/2))
    // recurrence -(n+10)*u(n+5)-(-2*n-18)*u(n+4)-(n+8)*u(n+3)-(4*n+10)*u(n)-(-4*n-8)*u(n-1) = 0
    super(0, "[[0],[-12,4],[10,-4],[0],[0],[-3,-1],[8,2],[-5,-1]]", "[1,1,1,1,1,0,-1]", 0);
  }
}
