package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360150 a(n) = Sum_{k=0..floor(n/3)} binomial(2*n-k,n-3*k).
 * @author Georg Fischer
 */
public class A360150 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360150() {
    // o.g.f. 1/(1-4*x)^(1/2)/(1-1/32/x^2*(1-(1-4*x)^(1/2))^5)
    // recurrence -n*((n-4)^2+11*n-32)*u(n)-(-9*(n-4)^3-133*(n-4)^2-454*n+1432)*u(n-1)-(24*(n-4)^3+350*(n-4)^2+1094*n-3464)*u(n-2)-(-17*(n-4)^3-247*(n-4)^2-752*n+2384)*u(n-3)-2*(2*n-5)*((n-4)^2+13*n-28)*u(n-4) = 0
    super(0, "[[0],[-120,98,-10,-4],[480,-408,43,17],[-600,554,-62,-24],[120,-178,25,9],[0,16,-3,-1]]", "[1,2,6,21,77]", 0);
  }
}
