package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360101 a(n) = Sum_{k=0..n} binomial(n+4*k-1,n-k) * Catalan(k).
 * @author Georg Fischer
 */
public class A360101 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360101() {
    // o.g.f. 1/2*(1-(1-4*x/(1-x)^5)^(1/2))/x*(1-x)^5
    // recurrence -(n+1)*u(n)-(-10*n+7)*u(n-1)-(19*n-56)*u(n-2)-(-20*n+90)*u(n-3)-(15*n-95)*u(n-4)-(-6*n+49)*u(n-5)-(n-10)*u(n-6) = 0
    super(0, "[[0],[10,-1],[-49,6],[95,-15],[-90,20],[56,-19],[-7,10],[-1,-1]]", "[1,1,7,40,234,1432,9078]", 0);
  }
}
