package irvine.oeis.a360;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360212 a(n) = Sum_{k=0..floor(n/3)} (-1)^k * binomial(2*n-5*k,n-3*k).
 * @author Georg Fischer
 */
public class A360212 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360212() {
    // o.g.f. 1/(1-4*x)^(1/2)/(1+1/2*x^2*(1-(1-4*x)^(1/2)))
    // recurrence -(n+5)*(33*(n-1)^2+265*n+259)*u(n+5)+2*(2*n+5)*(33*(n-1)^2+331*n+491)*u(n+4)-(n+5)*(33*(n-1)^2+265*n+259)*u(n+3)+2*(2*n+5)*(33*(n-1)^2+331*n+491)*u(n+2)-(n+5)*(33*(n-1)^2+265*n+259)*u(n)+2*(2*n+5)*(33*(n-1)^2+331*n+491)*u(n-1) = 0
    super(0, "[[0],[-240,746,-590,132],[0,-122,131,-33],[0],[-240,746,-590,132],[0,-122,131,-33],[-240,746,-590,132],[0,-122,131,-33]]", "[1,2,6,19,67,242,890]", 0);
  }
}
