package irvine.oeis.a362;
// Generated by gen_seq4.pl greprec3/holos at 2023-05-08 15:06

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A362153 Number of skew shapes in a 3 X n rectangle with no empty rows or columns.
 * @author Georg Fischer
 */
public class A362153 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A362153() {
    super(1, "[[0],[-12,20,-11,-8,-1],[36,-22,-7,4,1]]", "1,8,29,73,151,276,463", 0);
  }
}
