package irvine.oeis.a362;
// Generated by gen_seq4.pl holgrep/holos at 2023-05-08 18:43

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A362177 Expansion of e.g.f. exp(x * (1-3*x)).
 * @author Georg Fischer
 */
public class A362177 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A362177() {
    super(0, "[[0],[6,-6],[1],[-1]]", "1,1,-5,-17,73,481,-1709,-19025", 0);
  }
}
