package irvine.oeis.a062;
// Generated by gen_seq4.pl floorr at 2021-09-01 16:25

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.math.z.Z;
import irvine.oeis.FloorSequence;

/**
 * A062299 a(n) = floor(cot(Pi/(n+1))).
 * @author Georg Fischer
 */
public class A062299 extends FloorSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;
  /** Construct the sequence */
  public A062299() {
    super(1);
  }

  @Override
  public Z evalCR(final long mN) {
    return REALS.cot(CR.PI.divide(CR.valueOf(mN + 1))).floor();
  }

}
