package irvine.oeis.a143;
// Generated by gen_seq4.pl bindec at 2021-08-04 23:24

import irvine.oeis.BinaryToDecimalExpansionSequence;
import irvine.oeis.a143.A143731;

/**
 * A143735 Decimal expansion of A143731 interpreted as a binary fraction.
 * @author Georg Fischer
 */
public class A143735 extends BinaryToDecimalExpansionSequence {

  /** Construct the sequence */
  public A143735() {
    super(new A143731());
  }
}


